### PR TITLE
Change Query methods API and functionality

### LINKED ISSUE #68: void will not ignore the return of any Tarantool value
```lua
function create_or_update_etalon(args)
    ...
    return repository.put(space_name, ...)
end
```

```java
@Query(function = "call_service")
void callService(String name, Map<?, ?> args, Map<?, ?> options);
```

```
org.springframework.data.mapping.MappingException: Cannot read from object of type class java.util.ArrayList
	at org.springframework.data.tarantool.core.convert.MappingTarantoolReadConverter.read(MappingTarantoolReadConverter.java:106) ~[spring-data-tarantool-0.4.2.jar:na]
	at org.springframework.data.tarantool.core.convert.MappingTarantoolConverter.read(MappingTarantoolConverter.java:73) ~[spring-data-tarantool-0.4.2.jar:na]
	at org.springframework.data.tarantool.core.BaseTarantoolTemplate.mapToEntity(BaseTarantoolTemplate.java:385) ~[spring-data-tarantool-0.4.2.jar:na]
	at org.springframework.data.tarantool.core.TarantoolTemplate.lambda$null$1(TarantoolTemplate.java:87) ~[spring-data-tarantool-0.4.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at io.tarantool.driver.handlers.TarantoolResponseHandler.channelRead0(TarantoolResponseHandler.java:51) ~[cartridge-driver-0.6.0.jar:na]
	at io.tarantool.driver.handlers.TarantoolResponseHandler.channelRead0(TarantoolResponseHandler.java:23) ~[cartridge-driver-0.6.0.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

but if we remove `return ...` in lua, then everything will be ok

### LINKED ISSUE #69: Throws an error if @Tuple is not present in the repository when the @Query annotated method is used and return is Tuple(number indexed table)
It is hard to find the error, as there may be strange behavior, for example, returning empty value for a tuple or NPE

### LINKED ISSUE #78: RFC: Сonfusing annotation functionality of @Tuple
## Problem

Now we have the `@Tuple` annotation globally solving two different problems unrelated to each other:
1. Specifying a spacename in POJO(Entity) for the `SimpleTarantoolRepository` to work correctly (i.e. for the work of predefined functional), so that the functions access the required spacename.
2. An additional indication in the `Repository` for functions under the annotation `@Query`. An indication of what we expect in the response is **only** a serialized object - _Tuple(number indexed table)_, with the name of the space, to use the metadata to get keys for serialization. Without this `@Query` specification, the method expects an object (Map, or primitive data type) to be accepted. This is necessary, as I understand it, because converters that can accept both Tuple and other data types have not yet been implemented.

Due to the fact that the annotation performs two different functions, this confuses the user. There are problems with deciding where to specify the annotation, and where not to, and for what purposes. The user can interpret `@Tuple` as an indication of which space we want to use and its format (metadata), or as an indication of the return type of Tuple (in truth, this may not immediately come to mind).

## Suggested ways:
We can go two ways:
1) Change the API
  a) Break backwards compatibility
  b) Leave support for existing functionality
2) Write more detailed documentation with all notes

## Research
1) Change the API

Suggestions:
#### Move the work logic to `@Query`

 `@Tuple` in `Repository` is hardwired to `@Query`, so it can only be used in conjunction with `@Query`. We could move the functionality of `@Tuple` to `@Query` by adding additional parameters. Examples:
   * ```java
      @Query(function = "func_name", serialized = true, [spaceName="space_name"])
      ```
   *   ```java
        enum QueryReturnType {
           TUPLE,
           OBJECT
        }
        ...
        @Query(function = "func_name", returnType=QueryReturnType.TUPLE, spaceName="test_space")
        ```
etc.

**Break backwards compatibility**
We can completely remove the old `@Tuple` logic for `Repository`, or leave it and not use it as a depricate solution.

2) Document in detail the description

Explicitly indicate in the README, in the important section, or in bold that **`@Tuple` in the Repository is used to identify that the Tarantool output will accept _ONLY_ Tuples for domainClass returnType** - i.e. number indexed table.
For example, this could be `{{val1, val2}}` or `box.space.get (...)` etc. `@Tuple` in _Entity_ is needed so that Tarantool can use the predefined `SimpleTarantoolRepository` and access the correct spacename.

In README now:
> You can bind repository methods to calls of the stored functions in the Tarantool instance using the `@Query` annotation
with the stored function name specified in the `functionName` parameter.
For such methods, you can specify the stored function response format so that it will be parsed correctly. The response
format may be either an object (and a list of objects) or a tuple (and a list of tuples).

> The response format may be either an object (and a list of objects) or a tuple (and a list of tuples).  

It seems worth clarifying what an object is and what a tuple is. That the response format may not be an object but a map (map, string indexed table), and a tuple is a number indexed table `{{val1, val2}}`. It is also worth pointing out that we can return primitive data types.

> For such methods, you can specify the stored function response format so that it will be parsed correctly

It should be stated explicitly that if we specify `@Tuple`, then we accept **only** an array (number indexed tuple). And if we do not specify it, then map (string indexed table) or primitive data.

Also, JavaDoc comments are clearly outdated.
https://github.com/tarantool/cartridge-springdata/blob/b230551938351152fe786b59e86fc2a083d397cc/src/main/java/org/springframework/data/tarantool/core/mapping/Tuple.java#L12-L39

PS See also #30 to make API consistent.

### PR DESCRIPTION
**Pull request by ArtDu**
Redesigned custom methods API with `@Query` annotation in Repository interfaces:
* Instead of specifying the `@Tuple` annotation (indicated which stack of converters to use) on the methods, we use the output argument in the `@Query` annotation. Two arguments `AUTO` or `TUPLE` can be passed there, which corresponds to the `callForObject` and `callForTuple` methods.
* Made it so that `AUTO` can convert tuples too by adding some functionality in `callForObject`.
* Now custom `@Query` methods always use **ReturnType** to match the converter stack. **DomainType** is only used for predefined functions(`SimpleTarantoolRepository`).
* Added an exception if we expect `TUPLE,` but there is no metadata to convert it. Previously, we just received an empty object and could not figure out what was wrong.
* Since we are now looking at `returnType` we ignore the result if `void` is specified

Also for details see rfc: #78 

Closes #68 
Closes #69 
Closes #78

### CODE REVIEW

File: src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java [hunk 1]
```diff
@@ -89,7 +89,7 @@ public MappingTarantoolReadConverter(EntityInstantiators instantiators,
     @Nullable
     @SuppressWarnings("unchecked")
     public <R> R read(Class<R> targetClass, final @Nullable Object source) {
-        if (source == null) {
+        if (source == null || targetClass.equals(void.class)) {
```
Comment (ArtDu) [inline src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java:92]: This is not a final solution and it's better not to convert the result
to cartridge-java at all, only catch if there is an error. 
We can close ticket #68 and open a new ticket about what needs to be done in a more optimized version. Or, of course, we can just remove this commit and wait until we fix it normally

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java [hunk 2]
```diff
@@ -88,6 +99,67 @@ public TarantoolTemplate(
         );
     }
 
+    private <T> CallResultMapper<T, SingleValueCallResult<T>>
+    getDefaultWithTupleResultMapper(Class<T> entityClass, Optional<TarantoolSpaceMetadata> spaceMetadata) {
+        // blocked because it's not deepcopy
+        // MessagePackMapper defaultConverterWithTupleConverter = tarantoolClient.getConfig().getMessagePackMapper().copy();
+        MessagePackMapper defaultConverterWithTupleConverter = DefaultMessagePackMapperFactory.getInstance().defaultComplexTypesMapper();
```
Comment (ArtDu) [inline src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:106]: It seems that this is also worth starting a ticket or discussing

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java [hunk 3]
```diff
@@ -88,6 +99,67 @@ public TarantoolTemplate(
...
+                ArrayValue.class,
+                TarantoolTuple.class,
+                new TarantoolAutoResultConverter<>(
+                        new DefaultTarantoolTupleValueConverter(defaultConverterWithTupleConverter,
+                                                                spaceMetadata.orElse(null)),
+                        spaceMetadata.orElse(null)));
+
+        CallResultMapper<T, SingleValueCallResult<T>> resultMapper =
+                ((DefaultResultMapperFactoryFactory) tarantoolClient.getResultMapperFactoryFactory())
+                .getDefaultSingleValueMapper(defaultConverterWithTupleConverter, entityClass);
```
Comment (ArtDu) [inline src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:117]: This also looks bad, getDefaultSingleValueMapper can be obtained **only** from the DefaultResultMapperFactoryFactory. Note, without half a bottle you won't understand these identical SingleValueResultMappers ☹️

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java [hunk 4]
```diff
@@ -88,6 +99,67 @@ public TarantoolTemplate(
         );
     }
 
+    private <T> CallResultMapper<T, SingleValueCallResult<T>>
+    getDefaultWithTupleResultMapper(Class<T> entityClass, Optional<TarantoolSpaceMetadata> spaceMetadata) {
```
Comment (ArtDu) [inline src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:103]: It seems worth splitting this function into two: `getDefaultResultMapper` and `addTupleResultMapper`

**Comment by ArtDu** [comment]
It also seems worth renaming these classes, since now they are not consistent with each other:

_TarantoolRepository**TupleQueryExecutor**_
_TarantoolRepository**QueryObjectExecutor**_

File: README.md [hunk 5]
```diff
@@ -108,13 +108,13 @@ public interface BookRepository extends TarantoolRepository<Book, Long> {
 }
 ```
 
-The `@Tuple` annotation allows to specify the space name which schema will be used for forming the data tuples.
-You can add `@Tuple` on the `@Query` annotated method that specifies the space name for a specific stored function call.
-Also, you can add `@Tuple` annotation to the repository - it acts as a shortcut for specifying the tuple return format and space name for all custom methods
-in this repository. The `@Field` annotations provide custom names for the fields. It is necessary to have at least 
+The `@Tuple` annotation allows to specify the space name which schema will be used for forming the data tuples to sending
+and for mapping the incoming tuple into an object.
```
Comment (akudiyar) [inline README.md:112]: Please proof-read the texts with Nick before merging.

File: README.md [hunk 6]
```diff
@@ -108,13 +108,13 @@ public interface BookRepository extends TarantoolRepository<Book, Long> {
...
+You can omit the `@Tuple` annotation, then the connector will take the class name converted to snake_case.
+The `@Field` annotations provide custom names for the fields. It is necessary to have at least 
 one field marked with the `@Id` annotation.
 
-Extending `CrudRepository` causes CRUD methods being pulled into the
+Extending `TarantoolRepository` causes basic CRUD methods being pulled into the
```
Comment (akudiyar) [inline README.md:117]: Why is this changed? CrudRepository is a Spring Data class that the users should inherit from in their applications.

File: README.md [hunk 7]
```diff
@@ -219,80 +219,58 @@ The corresponding function in on Tarantool Cartridge router may look like (uses
...
-
-```java
-@Data
-@Tuple
-public class SampleUser {
-    private String name;
-    private String lastName;
-}
-```
+##### Specify output
```
Comment (akudiyar) [inline README.md:222]: The previous header and paragraph here was more clear to me. It tells about a use-case.

File: README.md [hunk 8]
```diff
@@ -219,80 +219,58 @@ The corresponding function in on Tarantool Cartridge router may look like (uses
...
-Here the space name is not specified neither in a `@Tuple` annotation on the repository interface, nor on the entity class, so it will be "book_entity" according to the entity class name, turned into "lower snake case".
-But for the "doSomething" method the space name will be overridden to "test_space".
-```java
-@Tuple
-public class BookEntity {
-  @Id
-  private Integer id;
-  private String name;
-}
+The second function returns a ready-made result with keys.
```
Comment (akudiyar) [inline README.md:249]: It is better to put the text closer to examples. Otherwise the reader will have to jump back and forth to the description.

File: README.md [hunk 9]
```diff
@@ -219,80 +219,58 @@ The corresponding function in on Tarantool Cartridge router may look like (uses
...
-end
-
-function get_predefined_users()
-    return { { name = "John", lastName = "Smith" }, { name = "Sam", lastName = "Smith" } }
+function get_age_by_name(name)
+    local user = crud.get("sample_user", name)
+    if user.rows[1] ~= nil then
+        return user.rows[1][2]
+    end
+    return nil
```
Comment (akudiyar) [inline README.md:269]: That's a very strange example. It either should be additional (explaining that nil values are parsed correctly) or a normal number should be returned.

File: README.md [hunk 10]
```diff
@@ -219,80 +219,58 @@ The corresponding function in on Tarantool Cartridge router may look like (uses
...
+Mapping happens by keys of table.
 
-public interface BookRepository extends TarantoolRepository<BookEntity, Integer> {
-    
-    // The space name here overrides to "test_space" for the current method
-    @Tuple("test_space") 
-    @Query(function = "do_something")
-    void doSomething(Book book);
-}
+Of course, the word `AUTO` means that we can accept any result, and therefore it can be specified in the first request as well.
```
Comment (akudiyar) [inline README.md:253]: Do we state somewhere that specifying AUTO explicitly is not needed and it is a default value?
TUPLE cannot be the default since this breaks the UX (AUTO is default in many other similar cases).

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 4 above)
Comment (akudiyar) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:103]: +

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 2 above)
Comment (akudiyar) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:106]: It is done in another way -- you create a new mapper and populate it with one from the config. There should be examples in tests or some other code around.

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 3 above)
Comment (akudiyar) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:117]: Too much repetition here, a helper function/factory or a new superficial mapper class may improve this a bit.

**Review by akudiyar — CHANGES_REQUESTED** [review]
Didn't read this in full, will continue later.

File: README.md (hunk 6 above)
Comment (ArtDu) [reply README.md:117]: In the example above, we inherit from `TarantoolRepository`, which just allows you to use CRUD methods to interact with Tarantool + adds methods from `PagingAndSortingRepository`. Nowhere in the code do we have an example where we inherit from `CrudRepository`, except `README.md`. Therefore, I propose to write `TarantoolRepository` everywhere, so as not to confuse the user, because the interface is the most functional complete, contains the `CrudRepository` and `PagingAndSortingRepository` methods

If you agree, then we should also change here to `TarantoolRepository`
image

File: README.md (hunk 7 above)
Comment (ArtDu) [reply README.md:222]: If you mean the previous one - the deleted paragraph, it was talking about the same thing as above. Those we have 2 paragraphs in the master talking about the same thing, only with different examples and this is more confusing, even take the same headings. `Proxy methods` and `Call stored functions`

image

File: README.md (hunk 8 above)
Comment (ArtDu) [reply README.md:249]: Put description between java code and lua code?

File: README.md (hunk 10 above)
Comment (ArtDu) [reply README.md:253]: We can think about this again, whether to make TUPLE or AUTO by default.
From the arguments that we came up with when designing the API, and which I give just below in the readme, these are:
1) TUPLE should be faster because we pass data without keys, TUPLE will teach the user to use the high perf option
2) SimpleTarantoolRepository - predefined functions work with TUPLE by default (differently don't work) and it becomes consistent the whole Repository API works with TUPLE by default

File: README.md (hunk 9 above)
Comment (ArtDu) [reply README.md:269]: What do you mean by normal number? default?

File: README.md (hunk 5 above)
Comment (ArtDu) [reply README.md:112]: Yes, as soon as we finish the readme, I'll tag our new head of documentation, Nick is now on another team

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 2 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:106]: So this is the question of how to populate it, there is a copy constructor
https://github.com/tarantool/cartridge-java/blob/a9bfb28812448e1298e2e23554f2f39b27ecddb7/src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java#L43-L53
but it doesn't do a deep copy. We could run through the converters, but this is a bad option and we don’t have access to the converters. Perhaps I did not understand you, please write in more detail what you meant or give an example

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 3 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:117]: I didn’t quite understand what kind of repetition you are talking about here, that we create a new converter with each request?

Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:117]: I would like to inherit the `DefaultResultMapperFactoryFactory` factory, but it is final in cartridge-java

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 4 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java]: Splited on `getDefaultComplexTypesMapper`, `registerTupleResultMapper`, `withDefaultSingleValueMapper` and `withDefaultSingleValueMapper`

File: README.md (hunk 6 above)
Comment (akudiyar) [reply README.md:117]: This breaks the way how using SpringData is intended to look like. The common interfaces like CrudRepository are being substituted by the engine with the most suitable implementation existing in the classpath, TarantoolRepository in this case. Of course, users are allowed to inherit TarantoolRepository directly for using Tarantool-specific methods and features, but in some real cases, the user may have switched from using another implementation (like Redis) or have them both, switching on one or another depending on the environment.

So, I agree that current examples need to be changed for TarantoolRespository, but we need a special example with CrudRepository along with this we the necessary remarks about how it is supposed to work. Also, we need a test that checks CrudRepository example to be working.

File: README.md (hunk 7 above)
Comment (akudiyar) [reply README.md:222]: Ah OK, I see. I wonder how it got duplicated +_+
BTW, here was a description of `functionName` parameter and it seems to be missing now.

File: README.md (hunk 8 above)
Comment (akudiyar) [reply README.md:249]: Nevermind, I took these changes wrong

File: README.md (hunk 10 above)
Comment (akudiyar) [reply README.md:253]: My arguments are the following:
 - Tuple output is "native" and therefore "default" for Tarantool. It is the way how box API works. So any option that specifies the "tuple" output should be the default.
 - The name "AUTO" makes the user assume that it is a default option. So in my POV, "AUTO" should correspond to the "tuple" output.
 - I suggest adding a new output type "LUA" for the other cases since it basically is an output of a Lua function.
 - Any other types are possible to be added further since I'm not completely sure that we can detect all types automatically.

File: README.md (hunk 9 above)
Comment (akudiyar) [reply README.md:269]: 1, 2, 10 -- any integer

File: src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java (hunk 1 above)
Comment (akudiyar) [reply src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java:93]: Do not get this change. Would you mind elaborating a bit more on why is this needed?

File: src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+
+/**
+ * Converter allows you to check if the received result is suitable for converting to {@link TarantoolResult},
+ * i.e. is the response structure appropriate and is the metadata present
+ *
+ * @param <V> the source MessagePack entity type
+ * @param <T> the target object type
+ * @author Artyom Dubinin
+ */
+public class TarantoolAutoResultConverter<V extends Value, T> implements ValueConverter<V, TarantoolResult<T>> {
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java:22]: Actually it is a "CRUD" converter. I think we need to have a special type for that and the corresponding naming.

Comment (akudiyar) [reply src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java:22]: A link in the description to the tarantool/crud README will be also necessary.

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryLookupStrategy.java [hunk 12]
```diff
@@ -37,18 +37,15 @@ public RepositoryQuery resolveQuery(final Method method, final RepositoryMetadat
 
         TarantoolQueryMethod queryMethod = new TarantoolQueryMethod(method, metadata, projectionFactory);
 
-        if (hasTupleAnnotation(metadata, queryMethod)) {
-            return new TarantoolTupleRepositoryQuery(operations, queryMethod);
+        if (isOutputExpectTuple(queryMethod)) {
+            return new TarantoolRepositoryTupleQuery(operations, queryMethod);
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryLookupStrategy.java:41]:
```suggestion
            return new TarantoolTupleRepositoryQuery(operations, queryMethod);
```
RepositoryQuery is a base class, be careful with changing the names since we need to keep the sources matching the Spring Data framework code.

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryMethod.java [hunk 13]
```diff
@@ -26,20 +26,6 @@ public TarantoolQueryMethod(Method method, RepositoryMetadata metadata, Projecti
         this.metadata = metadata;
     }
 
-    public Optional<String> getSpaceName() {
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryMethod.java:29]: And where did it go? So we won't have an option of specifying the space name in the `@Tuple` annotation?

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolRepositoryObjectQueryExecutor.java [hunk 14]
```diff
@@ -7,13 +7,14 @@
  * annotation and having result as object or list of objects
  *
  * @author Oleg Kuzentsov
+ * @author Artyom Dubinin
  */
-public class TarantoolRepositoryQueryObjectExecutor implements TarantoolRepositoryExecutor {
+public class TarantoolRepositoryObjectQueryExecutor implements TarantoolRepositoryExecutor {
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/query/TarantoolRepositoryObjectQueryExecutor.java:12]: See other comments about renaming. `RepositoryQuery` is a Spring Data class, we need to keep track of it.

File: src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java [hunk 15]
```diff
@@ -0,0 +1,18 @@
...
+ * but we cannot convert the values into object fields because missing metadata.
+ *
+ * @author Artyom Dubinin
+ */
+public class TarantoolMetadataMissingException extends TarantoolException {
+    private static final String prefix = "Missing metadata for space ";
+    private static final String postfix = " check name in Entity class";
+
+    public TarantoolMetadataMissingException(String spaceName) {
+        super(prefix + spaceName + postfix);
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java:16]: Use `String#format`, it is more readable

**Review by akudiyar — CHANGES_REQUESTED** [review]

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryMethod.java (hunk 13 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryMethod.java:29]: In the `@Query` method, we can't, since we removed the logic with `@Tuple`. In Entity we can get the name of the space

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryLookupStrategy.java (hunk 12 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryLookupStrategy.java:41]: Okay, then I'll think about how to make the names consistent, keeping this problem in mind

File: src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java (hunk 1 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java:93]: This is done because an error will occur if Tarantool returns any value, but springdata will not be able to convert it to `void`. So far this only happens for `callForObject`, but after this commit 731b415524645af5130b35fbc3f392b2d2ebbc85 will be for callForTuple as well. For example, for this test, where update returns an error, because we return the result, but in the interface `void`.

https://github.com/tarantool/cartridge-springdata/blob/01e3e8a4d621fc360ace54371551bdf1cedb4e37/src/test/java/org/springframework/data/tarantool/repository/support/RepositoryIntegrationTest.java#L145

https://github.com/tarantool/cartridge-springdata/blob/01e3e8a4d621fc360ace54371551bdf1cedb4e37/src/test/java/org/springframework/data/tarantool/repository/BookRepository.java#L20-L21

https://github.com/tarantool/cartridge-springdata/blob/01e3e8a4d621fc360ace54371551bdf1cedb4e37/src/test/resources/cartridge/app/roles/api_router.lua#L24-L26

It seems to me that there are two ways:
1) We close ticket #68 and say that if the user himself wrote garbage and his function from Tarantool returns a result, but in java it expects void, then this is an error. In this case, it is worth writing a suitable exception or using an existing one, because now it is difficult to understand what happened.
2) We ignore the result from Tarantool in carg-springdata or in carg-java. Then the API will be more flexible, but if the user wrote garbage, it will affect the perf and something else

File: README.md (hunk 6 above)
Comment (ArtDu) [reply README.md:117]: Thanks, understood the reason for using this interface. Then let's add some examples using `CrudRepository`

File: README.md (hunk 7 above)
Comment (ArtDu) [reply README.md:222]: Added a few words about `functionName` as it was in master

File: README.md (hunk 9 above)
Comment (ArtDu) [reply README.md:269]: Yes, you're right, it doesn't work that way. We can add `Optional<Integer>` and test in sources

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolRepositoryObjectQueryExecutor.java (hunk 14 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/query/TarantoolRepositoryObjectQueryExecutor.java]: renamed, now:
TarantoolTupleRepositoryQuery
TarantoolTupleRepositoryQueryExecutor
TarantoolObjectRepositoryQuery
TarantoolObjectRepositoryQueryExecutor

File: README.md (hunk 6 above)
Comment (ArtDu) [reply README.md]: Returned `CrudRepository` to the README, also added it to the real `BookRepository` code. Added a few words about TarantoolRepository

File: README.md (hunk 10 above)
Comment (ArtDu) [reply README.md:253]: I like the `LUA` option, but `AUTO` for tuples would be confusing. I think a good option is `TUPLE` **by default** and `LUA` to specify any other output.

File: src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java (hunk 15 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java]: Fixed

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java [hunk 16]
```diff
@@ -88,6 +103,81 @@ public TarantoolTemplate(
...
+    withDefaultSingleValueMapper(MessagePackMapper customMapper,
+                                 Class<T> entityClass) {
+        return mapperFactoryFactory
+                .getDefaultSingleValueMapper(customMapper, entityClass);
+    }
+
+    private <T> CallResultMapper<T, SingleValueCallResult<T>>
+    getAutoResultMapper(Class<T> entityClass, Optional<TarantoolSpaceMetadata> spaceMetadata) {
+        MessagePackMapper customMapper = getDefaultComplexTypesMapper();
+        registerTupleResultMapper(customMapper, spaceMetadata);
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:135]: Registering a new mapper will not affect the source mapper since the containers are copied. Don't worry about the nested mappers, they will not be affected by that.
Do you have any tests showing a problem with using the coping ctor here?

File: src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java [hunk 17]
```diff
@@ -106,7 +107,7 @@ public MappingTarantoolReadConverter(EntityInstantiators instantiators,
         } else if (source.getClass().equals(targetClass)) {
             return (R) source;
         } else {
-            throw new MappingException("Cannot read from object of type " + source.getClass());
+            throw new MappingException("Cannot map object of " + source.getClass() + " to object of " + targetClass);
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java:110]:
```suggestion
            throw new MappingException("Cannot map object of type " + source.getClass() + " to object of type " + targetClass);
```

File: src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java [hunk 18]
```diff
@@ -0,0 +1,73 @@
...
+import io.tarantool.driver.mappers.ValueConverter;
+import org.msgpack.value.ArrayValue;
+import org.msgpack.value.StringValue;
+import org.msgpack.value.Value;
+import org.msgpack.value.ValueFactory;
+
+import java.util.Map;
+
+/**
+ * Converter allows you to check if the received result is suitable for converting to {@link TarantoolResult},
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java:15]:
```suggestion
 * This converter provides an ability to check if the received result is suitable for converting to a {@link TarantoolResult},
```

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolObjectRepositoryQueryExecutor.java [hunk 19]
```diff
@@ -22,6 +23,13 @@ public TarantoolRepositoryQueryObjectExecutor(final TarantoolOperations operatio
     @Override
     public Object execute(Object[] parameters) {
         final Class<?> returnedType = queryMethod.getResultProcessor().getReturnedType().getReturnedType();
+        if (operations.getMappingContext().hasPersistentEntityFor(returnedType)) {
+            String spaceName = operations.getMappingContext().getRequiredPersistentEntity(returnedType).getSpaceName();
+            if (queryMethod.isCollectionQuery()) {
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/query/TarantoolObjectRepositoryQueryExecutor.java:28]: Looks like you can check if the space name is null here and do not repeat the `callForObject`/`callForObjectList` calls twice.

BTW, what does the `hasPersistentEntityFor` do?

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryMethod.java [hunk 20]
```diff
@@ -68,12 +45,12 @@ public Query getQueryAnnotation() {
...
     /**
-     * Returns the @Tuple annotation if set, null otherwise.
+     * Returns the response structure that the connector will expect from Tarantool specified in Query annotation
      *
-     * @return the @Tuple annotation if present.
+     * @return expected output structure
      */
-    public Tuple getTupleAnnotation() {
-        return AnnotatedElementUtils.findMergedAnnotation(method, Tuple.class);
+    public TarantoolSerializationType getQueryOutput() {
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/core/query/TarantoolQueryMethod.java:52]: Maybe `getQueryOutputType`?

File: src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java [hunk 21]
```diff
@@ -0,0 +1,15 @@
+package org.springframework.data.tarantool.exceptions;
+
+import io.tarantool.driver.exceptions.TarantoolException;
+
+/**
+ * When we expect only a flatted tuple,
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java:6]:
```suggestion
 * This exception is thrown when we expect a flattened tuple,
```

File: src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java [hunk 22]
```diff
@@ -0,0 +1,15 @@
...
+ * but we cannot convert the values into object fields because missing metadata.
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/exceptions/TarantoolMetadataMissingException.java:7]:
```suggestion
 * but we cannot convert the values into object fields because the metadata is missing.
```

File: src/main/java/org/springframework/data/tarantool/repository/Query.java [hunk 23]
```diff
@@ -25,4 +26,12 @@
      * @return the callable function name
      */
     String function();
+
+    /**
+     * Specify the response structure that the connector will expect from Tarantool by this parameter,
+     * the connector will use a certain stack of converters to translate the incoming result into a class object
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/repository/Query.java:32]: This phrase is redundant, speak of a use case here, not about the implementation details.

File: src/main/java/org/springframework/data/tarantool/repository/TarantoolSerializationType.java [hunk 24]
```diff
@@ -0,0 +1,45 @@
+package org.springframework.data.tarantool.repository;
+
+import org.springframework.data.tarantool.core.mapping.Tuple;
+
+/**
+ * Constants that indicate which internal data structure the connector should expect and which converter stack to use.
```
Comment (akudiyar) [inline src/main/java/org/springframework/data/tarantool/repository/TarantoolSerializationType.java:6]: I think this Javadoc needs to be updated. Also, try to not leak any unnecessary implementation details here.

**Review by akudiyar — CHANGES_REQUESTED** [review]

File: src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java (hunk 1 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/convert/MappingTarantoolReadConverter.java:93]: How can we understand that such a method is wrong on parsing? We don't know if Tarantool will return a value or not. `void` works fine if it returns nil same as returns nothing. I saw this code where nothing had to be returned in user's code and there needed void

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 16 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:135]: This is the problem, they are copied superficially, there was a problem that `TarantoolAutoResultConverter `, after adding, appeared in all requests. I'll try to add a test - reproducer

File: README.md [hunk 25]
```diff
@@ -219,80 +219,58 @@ The corresponding function in on Tarantool Cartridge router may look like (uses
...
-    @Query(function = "do_something")
-    Optional<Book> doSomething(Book book);
-}
+function get_predefined_user()
+    return { name = "John", age = 46 }
+end
 ```
+The first function returns users who are older than the specified age.
+In the Repository, we indicate that we expect `TUPLE`, because `crud.select` returns the result in compressed format, flatten tuples.
+The keys for mapping the result into a Java object are obtained by the connector by the class name in returnType or by the specified `@Tuple` above it.
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply README.md:247]: Yes, I had to write `method return type`

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java [hunk 26]
```diff
@@ -88,6 +103,81 @@ public TarantoolTemplate(
         );
     }
 
+    private MessagePackMapper getDefaultComplexTypesMapper() {
+        // blocked because it's not deepcopy
+        // MessagePackMapper defaultConverterWithTupleConverter = tarantoolClient.getConfig().getMessagePackMapper().copy();
+        return DefaultMessagePackMapperFactory
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:109]: I agree that the config from the client should remain. But to use now, we have to register one `TarantoolAutoResultConverter` with all the metadata. With each request, we cannot register a new converter.

> since you aren't going to change the inner mapper stack (returned from config), you just add wrappers around and for them take care of the proper copying

I didn't understand what kind of wrappers you mean, please describe in more detail

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 16 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:135]:
```diff
diff --git a/src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java b/src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java
index 8357163..b5c66be 100644
--- a/src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java
+++ b/src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java
@@ -105,10 +105,10 @@ public class TarantoolTemplate extends BaseTarantoolTemplate {

     private MessagePackMapper getDefaultComplexTypesMapper() {
         // blocked because it's not deepcopy
-        // MessagePackMapper defaultConverterWithTupleConverter = tarantoolClient.getConfig().getMessagePackMapper().copy();
-        return DefaultMessagePackMapperFactory
-                .getInstance()
-                .defaultComplexTypesMapper();
+        return tarantoolClient.getConfig().getMessagePackMapper().copy();
+//        return DefaultMessagePackMapperFactory
+//                .getInstance()
+//                .defaultComplexTypesMapper();
     }

     private void registerTupleResultMapper(MessagePackMapper customMapper,
```
If we change to copy, then after a few tests we will see that copying does not occur and `tarantoolClient.getConfig().getMessagePackMapper()`

image

File: src/main/java/org/springframework/data/tarantool/core/query/TarantoolObjectRepositoryQueryExecutor.java (hunk 19 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/query/TarantoolObjectRepositoryQueryExecutor.java:28]: We can't take `spaceName` if our `returnedType` is not `PersistentEntity` (example `Integer`). Because `operations.getMappingContext().getRequiredPersistentEntity(returnedType)` AFAIK will return null. `hasPersistentEntityFor` just checks if returnType is an entity

File: src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java (hunk 18 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java]: Fixed

File: README.md (hunk 25 above)
[the remark this answers is not in the document]
Comment (ArtDu) [reply README.md]: Fixed

File: README.md [hunk 27]
```diff
@@ -190,11 +190,11 @@ public class MyService {
 }
 ```
 
-#### Proxy methods in repositories
+#### Proxy Tarantool functions in repositories
 
 Consider we need to write a complex query in Lua, working with sharded data in Tarantool Cartridge. In this case
 we can expose this query as a public API function and map that function on a repository method via the `@Query`
-annotation:
+annotation specifying the functionName parameter:
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply README.md]: Fixed

File: src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java (hunk 11 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java]: In general, this converter is a repeat of this `TarantoolResultConverter`, only `canConvertValue` is added. Therefore, I redid it a little and now the class inherits from `TarantoolResultConverter`. It seems to me that the abbreviation `CRUD` is overloaded. 

@wey1and @vrogach2020 can you suggest a better option?

File: src/main/java/org/springframework/data/tarantool/repository/TarantoolSerializationType.java (hunk 24 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/repository/TarantoolSerializationType.java:6]: Now it is difficult to understand what we can return from Tarantool so that the connector can process it. We need to write more detailed information. The code of connectors with all the nesting of converters is difficult to understand, it seems to me that it is necessary to fix somewhere in general how this or that element works. Here, a superficial description of how and what we can return from Tarantool and how it is accepted looks perfect. 

If you want to remove the words about how we have mapping from various structures to a java object, then I suggest moving this description to some other place. Without these words, it is difficult to understand what is happening in the code in general, this will speed up the understanding of the code.

File: src/main/java/org/springframework/data/tarantool/repository/Query.java (hunk 23 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/repository/Query.java]: Rewrite

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 16 above)
Comment (wey1and) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:135]: I think that creating a new mapper and registering a new converter each time callForSingleResult is called is a bad idea. Looks like useless work. Why is it impossible to create the necessary mappers for all methods in interfaces once and use the ready ones?

File: src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java [hunk 28]
```diff
@@ -0,0 +1,67 @@
...
+    @Override
+    public boolean canConvertValue(Value value) {
+        return isSpaceMetadataExist() && (isNil(value) || isTuple(value) || isCrudResponse(value));
+    }
+
+    private boolean isSpaceMetadataExist() {
+        return spaceMetadata != null;
+    }
+
+    private boolean isNil(Value value) {
```
Comment (wey1and) [inline src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java:44]: Useless method

**Review by wey1and — CHANGES_REQUESTED** [review]

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 16 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:135]: This is a good point, but it's a connectors problem in general. In particular, a new mapper is now being created for each request in the master branch. There is a ticket for this issue about caching mappers https://github.com/tarantool/cartridge-java/issues/117 . Your idea is interesting, it will be necessary to think whether it is realistic to implement and whether there will be problems. But I propose to try realize it in another PR (we can leave a ticket on whether it is realistic to implement such a task)

File: src/main/java/org/springframework/data/tarantool/repository/Query.java [hunk 29]
```diff
@@ -25,4 +26,14 @@
...
+
+    /**
+     * Specify the response structure that the connector will expect from Tarantool by this parameter.
+     * This restriction can narrow the range of errors, for this purpose the parameter acts as a validation of the result.
+     * It can also help with performance by only expecting certain structures,
+     * because we do not check the result for belonging to another structure.
+     *
+     * @return expected output structure
+     */
+    TarantoolSerializationType output() default TarantoolSerializationType.TUPLE;
```
Comment (vrogach2020) [inline src/main/java/org/springframework/data/tarantool/repository/Query.java:38]: as discussed default shoud be AUTO

**Review by vrogach2020 — CHANGES_REQUESTED** [review]

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 16 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:135]: Discussed with @vrogach2020 that we should leave it as it is, not reuse the custom one until we fix this problem in [cartridge-java#166](https://github.com/tarantool/cartridge-java/issues/166).

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 2 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java]: Discussed with @vrogach2020 that we should leave it as it is, not reuse the custom one until we fix this problem in [cartridge-java#166](https://github.com/tarantool/cartridge-java/issues/166).

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java:109]: Discussed with @vrogach2020 that we should leave it as it is, not reuse the custom one until we fix this problem in [cartridge-java#166](https://github.com/tarantool/cartridge-java/issues/166).

File: src/main/java/org/springframework/data/tarantool/core/BaseTarantoolTemplate.java [hunk 30]
```diff
@@ -356,8 +355,12 @@ protected TupleOperations setNonNullFieldsFromTuple(TarantoolTuple tuple) {
             SingleValueCallResult<TarantoolResult<TarantoolTuple>>>
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/BaseTarantoolTemplate.java:355]: @wey1and There is no point then in checking the condition for `void`, because we should not throw an error, if we do not have a metadata, but **returnType** is `void`.

File: src/main/java/org/springframework/data/tarantool/repository/Query.java (hunk 29 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/repository/Query.java]: Fixed

File: README.md [hunk 31]
```diff
@@ -219,80 +219,58 @@ The corresponding function in on Tarantool Cartridge router may look like (uses
...
 
 ```lua
-function returning_sample_user_object()
-    return { name = "John", lastName = "Smith" }
-end
-
-function get_predefined_users()
-    return { { name = "John", lastName = "Smith" }, { name = "Sam", lastName = "Smith" } }
+function get_age_by_name(name)
+    local user = crud.get("sample_user", name)
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply README.md:265]: Added
```lua
local user, err = crud.get("sample_user", name)
if err ~= nil then
    return user, err
end
```

[the remark this answers is not in the document]
Comment (ArtDu) [reply README.md:265]: Added
```lua
local user, err = crud.get("sample_user", name)
if err ~= nil then
    return user, err
end
```

File: src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java (hunk 11 above)
Comment (ArtDu) [reply src/main/java/org/springframework/data/tarantool/core/mappers/TarantoolAutoResultConverter.java]: With @vrogach2020 we decided that because we are left with the following API:
```
AUTO - default
TUPLE
```
then this converter can be left as it is now named - `TarantoolAutoResultConverter`

File: src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java (hunk 2 above)
Comment (vrogach2020) [reply src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java]: Described problem in #84

File: README.md (hunk 5 above)
Comment (vrogach2020) [reply README.md:112]: Added action point for readme review #85
